version: "3.8"

services:
  terraform:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: terraform-container
    volumes:
      - ../terraform:/workspace 
      - terraform-state:/terraform_data # separate volume for Terraform state
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh
    working_dir: /workspace
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  terraform-state: 
